### ISSUE TITLE
Input Form

### ISSUE THREAD

**Issue by maje02** [maje02/make_it_stay#30]
## Value statement 
As a **user** 
I need **to add new places if they are not in the list** 
so that **the next user will find these spots easily** 
## Description (Text, Scribble, Wireframe, Design)
- a form is on an extra page, the entry will be added to list in home and will be shown on the map
## Acceptance criteria
- [ ] new places can be added in a form
- [ ] they will show up in the list directly
## Tasks
- [ ] in the navigation there is an "add", a click on it opens the form
- [ ] create a form, mandatory fields: name, addressdetails, opening times, description, categories, not mandatory: contactdetails (phone, mail, website)
- [ ] upload new information to firestore
## Size
large
